### ISSUE TITLE
Update the homepage link on PyPi

### ISSUE THREAD

**Issue by parthea** [GoogleCloudPlatform/google-auth-library-python-httplib2#4]
The homepage link on https://pypi.python.org/pypi/google-auth-httplib2 is currently pointing to https://github.com/GoogleCloudPlatform/google-auth-library-python but I think it should be https://github.com/GoogleCloudPlatform/google-auth-library-python-httplib2. 

Separately, is there a readthedocs.io page for this repo?
For example, for google-auth-oauthlib the link is http://google-auth-oauthlib.readthedocs.io/en/latest/

**Comment by jonparrott** [comment]
@dhermes got this in 136da2c I believe. :)

> Separately, is there a readthedocs.io page for this repo?

Nope, and it's intentional. We only created this library to help legacy first-party clients (notably google-api-python-client and temporarily google-cloud-python) move from oauth2client to google-auth. We're actively discouraging the continued use of httplib2.

**Comment by drigz** [comment]
This is still an issue - it took me a couple of minutes of grepping to find this repo.

See here: https://pypi.python.org/pypi/google-auth-httplib2

Maybe another release is required?

**Comment by jonparrott** [comment]
@drigz yeah, published.
